package com.rovena.garage.domain.model

/**
 * Shared enums used across the domain layer. These are pure Kotlin (no Android
 * dependency) so they can be unit tested on a plain JVM and shared between the
 * Room entities (data layer) and the UI (presentation layer).
 */

enum class FuelType {
    PETROL, DIESEL, HYBRID, PLUG_IN_HYBRID, ELECTRIC, LPG, OTHER
}

enum class TransmissionType {
    MANUAL, AUTOMATIC, CVT, DCT, OTHER
}

enum class MaintenanceCategory {
    ENGINE_OIL, OIL_FILTER, AIR_FILTER, CABIN_FILTER, FUEL_FILTER, SPARK_PLUGS,
    BRAKE_PADS, BRAKE_DISCS, TIRES, BATTERY, COOLANT, TRANSMISSION_FLUID,
    TIMING_BELT, SERPENTINE_BELT, SUSPENSION, STEERING, AC, ELECTRICAL,
    ENGINE, TRANSMISSION, OTHER
}

enum class ExpenseCategory {
    FUEL, MAINTENANCE, REPAIRS, INSURANCE, REGISTRATION, TIRES, CAR_WASH,
    PARKING, FINES, PARTS, ACCESSORIES, INSPECTION, OTHER
}

enum class DocumentType {
    REGISTRATION, INSURANCE, INSPECTION, PURCHASE_CONTRACT, MAINTENANCE_INVOICE,
    RECEIPT, OTHER
}

enum class InspectionCategoryGroup { EXTERIOR, INTERIOR, MECHANICAL }

enum class InspectionItemStatus { GOOD, ATTENTION, PROBLEM, UNKNOWN }

enum class ReminderBasis { MILEAGE, DATE, BOTH }

enum class TimelineEventType { FUEL, MAINTENANCE, EXPENSE, DOCUMENT, INSPECTION, REMINDER, VEHICLE_UPDATE }

enum class HealthStatus { EXCELLENT, GOOD, FAIR, ATTENTION_NEEDED, CRITICAL, NOT_ENOUGH_DATA }

enum class DueStatus { UPCOMING, DUE_SOON, DUE, OVERDUE }

enum class HealthCategory {
    MAINTENANCE_RECENCY,
    OVERDUE_MAINTENANCE,
    BRAKES,
    TIRES,
    BATTERY,
    FLUIDS,
    ENGINE_SERVICE,
    TRANSMISSION_SERVICE,
    DOCUMENTATION
}

enum class AppCurrency(val code: String) {
    JOD("JOD"), USD("USD"), EUR("EUR"), GBP("GBP"),
    SAR("SAR"), AED("AED"), EGP("EGP"), TRY("TRY"), CUSTOM("CUSTOM")
}

enum class DistanceUnit { KM, MILES }

enum class FuelEconomyUnit { L_100KM, MPG }

enum class AppLanguage(val tag: String) { ENGLISH("en"), ARABIC("ar"), FRENCH("fr"), SPANISH("es") }

enum class AppThemeMode { LIGHT, DARK, SYSTEM }

/**
 * Individual checklist items for a vehicle inspection, grouped by
 * [InspectionCategoryGroup]. "WINDOWS" is intentionally usable under both
 * EXTERIOR (glass condition) and INTERIOR (winding/electric mechanism).
 */
enum class InspectionItemKey {
    // EXTERIOR
    PAINT, BODY, DOORS, EXT_WINDOWS, LIGHTS, MIRRORS, TIRES, WHEELS, CHASSIS,
    // INTERIOR
    SEATS, DASHBOARD, INT_AC, INT_WINDOWS, AUDIO, ELECTRONICS, INTERIOR_CONDITION,
    // MECHANICAL
    ENGINE, TRANSMISSION, BRAKES, SUSPENSION, STEERING, COOLING, FLUIDS, BATTERY
}

/** What a [VehiclePhoto] record is attached to. */
enum class PhotoLinkedType { VEHICLE, MAINTENANCE, INSPECTION, INSPECTION_ITEM, EXPENSE, DOCUMENT }

enum class BackupRecordType { CREATED, RESTORED, EXPORTED, IMPORTED }

/**
 * How urgent a single reminder notification is, derived from how close (or
 * how overdue) the underlying due date/mileage is - never a fabricated
 * judgment about the vehicle itself. Drives both the Android notification's
 * priority and the per-severity mute toggles in Settings.
 */
enum class NotificationSeverity { CRITICAL, IMPORTANT, UPCOMING }

/**
 * Where a reminder notification came from, so Settings can offer per-category
 * mute toggles. DOCUMENT reminders are auto-generated by [com.rovena.garage]'s
 * DocumentRepository from a document's expiry date; GENERAL covers every
 * reminder the user created directly (mileage/date reminders not tied to a
 * document).
 */
enum class ReminderCategory { DOCUMENT, GENERAL }
